version: "3"

services:

  db:
    image: mysql:5.6
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    networks:
      - picweb
    environment:
      MYSQL_USER: picweb
      MYSQL_PASSWORD: picweb
      MYSQL_DATABASE: picweb
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
      - 3306:3306

  web:
    image: picweb:latest
    restart: always
    networks:
      - picweb
    ports:
      - 80:80
    links:
      - "db:database"

networks:
  picweb:

volumes:
  db-data: