version: "3"

services:

  db:
    image: mysql:5.6
    volumes:
      - db-data:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/dump.sql
    restart: always
    networks:
      - picweb2
    environment:
      MYSQL_USER: picweb2
      MYSQL_PASSWORD: picweb2
      MYSQL_DATABASE: picweb2
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'

  web:
    image: picweb2:latest
    build: 
      context: .
    restart: always
    networks:
      - picweb2
    ports:
      - 80:80
    links:
      - "db:database"

networks:
  picweb2:

volumes:
  db-data: